// Command fetch_fixture_gen emits static DOM/render/relevance vectors from the Go oracle.
// It is intentionally a generator, not a second handwritten specification.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/net/html"

	"github.com/danieljustus/symaira-browse/internal/fetch/agentdom"
	"github.com/danieljustus/symaira-browse/internal/fetch/dom"
	"github.com/danieljustus/symaira-browse/internal/fetch/relevance"
	"github.com/danieljustus/symaira-browse/internal/fetch/render"
	"github.com/danieljustus/symaira-browse/internal/fetch/semantic"
)

const oracleCommit = "652453d1595fc302bd69c328e7da8a21dbee28b9"

var sourceFiles = []string{
	"internal/fetch/agentdom/builder.go", "internal/fetch/agentdom/document.go",
	"internal/fetch/dom/extract.go", "internal/fetch/dom/filter.go",
	"internal/fetch/semantic/classify.go", "internal/fetch/semantic/islands.go",
	"internal/fetch/semantic/score.go", "internal/fetch/render/frontmatter.go",
	"internal/fetch/render/images.go", "internal/fetch/render/json.go",
	"internal/fetch/render/markdown.go", "internal/fetch/render/schema.go",
	"internal/fetch/render/text.go", "internal/fetch/relevance/relevance.go",
}

type vector struct {
	Name           string          `json:"name"`
	HTML           string          `json:"html"`
	Query          string          `json:"query"`
	TopK           int             `json:"top_k"`
	Title          string          `json:"title"`
	Lang           string          `json:"lang"`
	CleanHTML      string          `json:"clean_html"`
	Markdown       string          `json:"markdown"`
	Document       json.RawMessage `json:"document"`
	RankedHeadings []string        `json:"ranked_headings"`
}

type fixture struct {
	OracleCommit string            `json:"oracle_commit"`
	GeneratedBy  string            `json:"generated_by"`
	SourceDigest string            `json:"source_digest"`
	VectorCount  int               `json:"vector_count"`
	Comparison   map[string]string `json:"comparison"`
	Vectors      []vector          `json:"vectors"`
}

func main() {
	out := flag.String("out", "port/fixtures/fetch/static.json", "fixture path")
	check := flag.Bool("check", false, "compare regenerated bytes with the committed fixture")
	flag.Parse()
	result := generate()
	data, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		panic(err)
	}
	data = append(data, '\n')
	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			panic(fmt.Errorf("read fixture: %w", err))
		}
		if !bytes.Equal(existing, data) {
			panic(fmt.Sprintf("fixture drift: regenerate %s deliberately", *out))
		}
		fmt.Printf("checked %s (%d vectors, source %s)\n", *out, result.VectorCount, result.SourceDigest)
		return
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*out, data, 0644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s (%d vectors, source %s)\n", *out, result.VectorCount, result.SourceDigest)
}

func generate() fixture {
	inputs := []struct {
		name, html, query string
		topK              int
	}{
		{"malformed-cleanup", `<html lang="en"><head><title>  Static Guide </title><script>drop()</script></head><body><main id="content" data-noise="x"><h1>Static Guide</h1><p>Keep <strong>important</strong> content.</p><div hidden>secret</div><a href="https://example.com/docs">Docs</a></main><script type="application/ld+json">{"@type":"Article","headline":"Static Guide"}</script></body></html>`, "important", 1},
		{"metadata-links", `<html lang="pt-BR"><head><title>Links</title><style>.x{}</style></head><body><article class="article"><h2>Fetch details</h2><p>Reliable static fetching preserves metadata and useful links.</p><a href="https://example.com/fetch">Fetch docs</a><img src="/hero.png" alt="Hero"></article><nav><a href="/menu">Menu</a></nav></body></html>`, "metadata", 2},
		{"aria-hidden", `<html lang="fr"><body><main><h1>Visible résumé</h1><p aria-hidden="true">Do not include this.</p><p style="display: none">Also hidden.</p><p class="sr-only">Secret assistive text.</p><p>Keep this sentence.</p></main></body></html>`, "visible", 1},
		{"preloaded-json", `<html lang="ja"><head><title>状態</title><script id="__NEXT_DATA__">{"page":"home","ok":true}</script><script id="preloaded-state">{"items":[1,2]}</script></head><body><main><h1>日本語の状態</h1><p>Unicode content survives static extraction.</p></main></body></html>`, "unicode", 3},
		{"role-controls", `<html><body><main><h1>Controls</h1><div role="button" aria-label="Run">Run</div><div role="textbox" placeholder="Name"></div><div role="combobox">Choose</div></main></body></html>`, "controls", 0},
		{"form-controls", `<html><body><form action="/submit" method="post"><label for="name">Name</label><input id="name" type="text" value="Ada"><button type="submit">Send</button><select name="kind"><option>One</option></select></form></body></html>`, "name", 0},
		{"lists-blockquotes", `<html><body><article><h2>Examples</h2><ul><li>First item</li><li>Second item</li></ul><blockquote>Quoted words.</blockquote><pre><code>let x = 1;</code></pre></article></body></html>`, "item", 2},
		{"images-and-empty-links", `<html><body><main><h2>Media</h2><img src="/a.png" alt="A"><img src="/ignored.png"><a href="/one">One</a><a href="">No target</a><br>tail</main></body></html>`, "media", 1},
		{"language-casing", `<HTML LANG="zh-Hant"><HEAD><TITLE>  Mixed Case  </TITLE></HEAD><BODY><SECTION id="story"><P>Mixed case tags remain semantic.</P></SECTION></BODY></HTML>`, "semantic", 1},
		{"nested-sections", `<html><body><main><section><h2>Alpha</h2><p>alpha paragraph with enough content for the static corpus.</p></section><section><h2>Beta</h2><p>beta paragraph with different relevance terms.</p></section></main></body></html>`, "beta", 1},
		{"data-graph", `<html><head><script type="application/ld+json">{"@graph":[{"@type":"Recipe","name":"Soup"}]}</script></head><body><article><h1>Soup</h1><p>A recipe with ingredients and method.</p></article></body></html>`, "recipe", 1},
		{"malformed-json", `<html><head><script type="application/ld+json">not-json</script></head><body><main><p>Malformed data does not become a document island.</p></main></body></html>`, "malformed", 0},
		{"table-definition", `<html><body><main><h2>Reference</h2><table><tr><th>Term</th><th>Meaning</th></tr><tr><td>Fetch</td><td>Retrieve a resource.</td></tr></table><dl><dt>URL</dt><dd>Uniform resource locator.</dd></dl></main></body></html>`, "fetch", 2},
		{"whitespace", `<html><body><article><h1>Whitespace</h1><p>Many\n   spaces\tbecome one.</p><p>Second paragraph.</p></article></body></html>`, "spaces", 0},
		{"hidden-class", `<html><body><main class="content"><p class="hide">gone</p><p class="visible">stays</p><div style="visibility:hidden">gone too</div></main></body></html>`, "stays", 0},
		{"anchors", `<html><body><main><h2>Links</h2><p><a href="https://example.test/a">Alpha</a> and <a href="#local">Local</a>.</p></main></body></html>`, "alpha", 0},
		{"unicode-budget", `<html lang="de"><body><main><h1>Grüße 🌍</h1><p>Äpfel, Öl und Straße sind Unicode.</p></main></body></html>`, "straße", 1},
		{"empty-body", `<html><head><title>Empty</title></head><body></body></html>`, "", 0},
		{"article-class", `<html><body><div class="post"><h2>Post</h2><p>Article-like content in a div is still rendered.</p></div><footer>Footer navigation</footer></body></html>`, "article", 1},
		{"all-cleanup", `<html><body><main><script>x</script><style>x</style><noscript>x</noscript><svg>x</svg><iframe>x</iframe><object>x</object><embed>x</embed><canvas>x</canvas><audio>x</audio><video>x</video><template>x</template><picture>x</picture><p>survives</p></main></body></html>`, "survives", 1},
	}
	inputs = append(inputs, trackedPipelineInputs()...)
	result := fixture{
		OracleCommit: oracleCommit,
		GeneratedBy:  "scripts/rust-port/fetch_fixture_gen.go",
		SourceDigest: sourceDigest(),
		VectorCount:  len(inputs),
		Comparison: map[string]string{
			"FETCH-006": "bytes",
			"FETCH-007": "bytes",
			"FETCH-008": "json-semantic",
		},
	}
	for _, input := range inputs {
		result.Vectors = append(result.Vectors, makeVector(input.name, input.html, input.query, input.topK))
	}
	return result
}

func trackedPipelineInputs() []struct {
	name, html, query string
	topK              int
} {
	entries, err := os.ReadDir("internal/fetch/pipeline/testdata")
	if err != nil {
		panic(err)
	}
	queries := map[string]struct {
		query string
		topK  int
	}{
		"news_article.html": {query: "mars", topK: 1},
		"nav_heavy.html":    {query: "energy", topK: 1},
		"nextjs_shell.html": {query: "page", topK: 1},
		"form_page.html":    {query: "name", topK: 1},
		"spa_shell.html":    {query: "", topK: 0},
		"spa_shell.md":      {query: "", topK: 0},
	}
	inputs := make([]struct {
		name, html, query string
		topK              int
	}, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		data, err := os.ReadFile(filepath.Join("internal/fetch/pipeline/testdata", name))
		if err != nil {
			panic(err)
		}
		caseConfig := queries[name]
		inputs = append(inputs, struct {
			name, html, query string
			topK              int
		}{
			name: name, html: string(data), query: caseConfig.query, topK: caseConfig.topK,
		})
	}
	return inputs
}

func sourceDigest() string {
	hash := sha256.New()
	for _, path := range sourceFiles {
		data, err := os.ReadFile(path)
		if err != nil {
			panic(err)
		}
		hash.Write([]byte(path))
		hash.Write([]byte{0})
		hash.Write(data)
		hash.Write([]byte{0})
	}
	return hex.EncodeToString(hash.Sum(nil))
}

// canonicalizeInteractiveAttributes removes Go map-iteration nondeterminism from
// the oracle's interactive-element suffixes before the fixture is frozen.
func canonicalizeInteractiveAttributes(markdown string) string {
	lines := strings.Split(markdown, "\n")
	for i, line := range lines {
		if !strings.HasPrefix(line, "- **") {
			continue
		}
		if typeStart := strings.Index(line, " ("); typeStart >= 0 {
			if placeholderStart := strings.Index(line, " ["); placeholderStart > typeStart {
				placeholderEnd := strings.Index(line[placeholderStart:], "]")
				typeEnd := strings.Index(line[typeStart:], ")")
				if placeholderEnd > 0 && typeEnd > 0 {
					placeholderEnd += placeholderStart
					typeEnd += typeStart
					placeholder := line[placeholderStart : placeholderEnd+1]
					kind := line[typeStart : typeEnd+1]
					line = line[:typeStart] + placeholder + kind + line[placeholderEnd+1:]
				}
			}
		}
		lines[i] = line
	}
	return strings.Join(lines, "\n")
}

func makeVector(name, source, query string, topK int) vector {
	tree, err := dom.Parse([]byte(source))
	if err != nil {
		panic(err)
	}
	rawIslands := semantic.ExtractIslands(tree.Root, 1<<20)
	dom.Filter(tree.Root)
	var clean []byte
	if err := html.Render(writer{&clean}, tree.Root); err != nil {
		panic(err)
	}
	best := semantic.BestBlock(tree.Root, 20)
	doc := &agentdom.Document{URL: "https://example.com/source", Title: tree.Title, Lang: tree.Lang}
	builder := agentdom.NewBuilder(0)
	builder.Build(best, doc)
	for _, island := range rawIslands {
		doc.Islands = append(doc.Islands, agentdom.DataIsland{Source: island.Source, JSON: island.JSON})
	}
	markdown, err := render.Markdown(doc, best, true)
	if err != nil {
		panic(err)
	}
	markdown = canonicalizeInteractiveAttributes(markdown)
	sections := relevance.SplitMarkdownSections(markdown)
	ranked := relevance.RankSections(query, sections, topK)
	headings := make([]string, 0, len(ranked))
	for _, section := range ranked {
		headings = append(headings, section.Heading)
	}
	encoded, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		panic(err)
	}
	return vector{Name: name, HTML: source, Query: query, TopK: topK, Title: tree.Title, Lang: tree.Lang, CleanHTML: string(clean), Markdown: markdown, Document: encoded, RankedHeadings: headings}
}

type writer struct{ p *[]byte }

func (w writer) Write(p []byte) (int, error) { *w.p = append(*w.p, p...); return len(p), nil }
