#!/usr/bin/env python3
"""Generate MCP raw-frame fixtures and the Rust registry from the Go oracle."""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path

ORACLE_COMMIT = "652453d1595fc302bd69c328e7da8a21dbee28b9"
SOURCE_FILES = (
    "cmd/symbrowse/mcp.go",
    "internal/mcp/profiles.go",
    "internal/mcp/server.go",
    "internal/mcp/tools.go",
)
INITIALIZE = {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params": {
        "protocolVersion": "2024-11-05",
        "capabilities": {},
        "clientInfo": {"name": "fixture", "version": "0"},
    },
}

def compact(value: object) -> bytes:
    return (json.dumps(value, separators=(",", ":"), ensure_ascii=False) + "\n").encode()


def framed(value: object) -> bytes:
    body = compact(value).rstrip(b"\n")
    return b"Content-Length: " + str(len(body)).encode() + b"\r\n\r\n" + body


def oracle_environment() -> tuple[tempfile.TemporaryDirectory[str], dict[str, str]]:
    temporary = tempfile.TemporaryDirectory(prefix="symbrowse-mcp-oracle-")
    base = Path(temporary.name)
    runtime = base / "runtime"
    data = base / "data"
    home = base / "home"
    for path in (runtime, data, home):
        path.mkdir(mode=0o700)
    environment = {
        key: value
        for key, value in os.environ.items()
        if key not in {"SYMBROWSE_NO_AUTOSTART", "SYMBROWSE_RUNTIME_DIR", "SYMBROWSE_USER_DATA_DIR"}
    }
    environment.update({
        "HOME": str(home),
        "XDG_RUNTIME_DIR": str(runtime),
        "SYMBROWSE_USER_DATA_DIR": str(data),
    })
    return temporary, environment


def run(oracle: Path, frames: Sequence[object], *args: str) -> tuple[bytes, bytes]:
    data = b"".join(compact(frame) for frame in frames)
    temporary, environment = oracle_environment()
    try:
        proc = subprocess.run(
            [str(oracle), "mcp", "--engine", "static", *args],
            input=data,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=True,
            env=environment,
        )
        return proc.stdout, proc.stderr
    finally:
        temporary.cleanup()


def write_pair(root: Path, name: str, oracle: Path, frames: Sequence[object], *args: str, check: bool = False) -> dict[str, str]:
    out, err = run(oracle, frames, *args)
    if err:
        raise SystemExit(f"oracle wrote stderr for {name}: {err!r}")
    fixture_dir = root / "testdata" / "port" / "mcp"
    fixture_dir.mkdir(parents=True, exist_ok=True)
    input_data = b"".join(compact(frame) for frame in frames)
    sync_file(fixture_dir / f"{name}.in", input_data, check)
    if name == "tool_error" and sys.platform in {"darwin", "win32"}:
        # The v0.8.0 Go oracle uses a Unix transport that is unavailable on
        # these hosts. Its true result is therefore the transport error,
        # before the static engine can apply the loopback policy. Keep this
        # platform-specific oracle observation explicit; do not commit a
        # path-bearing fixture or turn the error into a pass.
        response = json.loads(out)
        error = response["result"]["_meta"]["symaira.dev/tool_error"]
        if error.get("code") != "daemon_unavailable":
            raise SystemExit(f"{sys.platform} Go oracle tool_error code changed: {error.get('code')!r}")
        # The transport metadata may contain an environment-specific socket
        # or log path. It is deliberately not persisted as a fixture.
    else:
        sync_file(fixture_dir / f"{name}.out", out, check)
    return {"input": f"{name}.in", "output": f"{name}.out"}


def source_hashes(root: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for path in SOURCE_FILES:
        data = subprocess.check_output(["git", "show", f"{ORACLE_COMMIT}:{path}"], cwd=root)
        result[path] = hashlib.sha256(data).hexdigest()
    return result


def rust_raw(value: str) -> str:
    for hashes in range(3, 12):
        delimiter = "#" * hashes
        if f'"{delimiter}' not in value:
            return f'r{delimiter}"{value}"{delimiter}'
    raise SystemExit("could not choose a Rust raw-string delimiter")


def generate_registry(root: Path, all_output: bytes, check: bool) -> None:
    response = json.loads(all_output)
    tools = response["result"]["tools"]
    registry = root / "crates" / "symbrowse-mcp" / "src" / "generated_registry.rs"
    registry.parent.mkdir(parents=True, exist_ok=True)
    text = "// @generated by scripts/rust-port/mcp_fixture_gen.py; do not edit.\n"
    text += "pub const ALL_TOOLS_JSON: &str = " + rust_raw(json.dumps(tools, separators=(",", ":"), ensure_ascii=False)) + ";\n"
    if check:
        existing = registry.read_text(encoding="utf-8") if registry.exists() else ""
        if existing != text:
            raise SystemExit(f"generated registry is stale: {registry}")
    else:
        registry.write_text(text, encoding="utf-8")


def sync_file(path: Path, content: bytes, check: bool) -> None:
    if check:
        existing = path.read_bytes() if path.exists() else b""
        if existing != content:
            raise SystemExit(f"MCP fixture is stale: {path}")
    else:
        path.write_bytes(content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--oracle", type=Path, required=True)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = args.root.resolve()
    oracle = args.oracle.resolve()
    if not oracle.is_file():
        raise SystemExit(f"oracle binary not found: {oracle}")

    fixture_dir = root / "testdata" / "port" / "mcp"
    fixture_names: dict[str, dict[str, str]] = {}
    fixture_names["initialize"] = write_pair(
        root, "initialize", oracle, [INITIALIZE], check=args.check
    )
    fixture_names["framed_initialize"] = write_pair_raw(
        root, "framed_initialize", oracle, framed(INITIALIZE), check=args.check
    )
    fixture_names["initialized"] = write_pair(
        root,
        "initialized",
        oracle,
        [{"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}}],
        check=args.check,
    )
    list_request = [{"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}}]
    fixture_names["tools_core"] = write_pair(
        root, "tools_core", oracle, list_request, check=args.check
    )
    fixture_names["tools_nav"] = write_pair(
        root, "tools_nav", oracle, list_request, "--tools", "nav", check=args.check
    )
    fixture_names["tools_all"] = write_pair(
        root, "tools_all", oracle, list_request, "--tools", "all", check=args.check
    )
    fixture_names["malformed"] = write_pair_raw(
        root, "malformed", oracle, b"{not-json}\n", check=args.check
    )
    fixture_names["unknown_method"] = write_pair(
        root,
        "unknown_method",
        oracle,
        [{"jsonrpc": "2.0", "id": 3, "method": "bogus", "params": {}}],
        check=args.check,
    )
    fixture_names["unknown_tool"] = write_pair(
        root,
        "unknown_tool",
        oracle,
        [{"jsonrpc": "2.0", "id": 2, "method": "tools/call", "params": {"name": "nope", "arguments": {}}}],
        check=args.check,
    )
    fixture_names["missing_argument"] = write_pair(
        root,
        "missing_argument",
        oracle,
        [{"jsonrpc": "2.0", "id": 2, "method": "tools/call", "params": {"name": "open", "arguments": {}}}],
        check=args.check,
    )
    fixture_names["tool_error"] = write_pair(
        root,
        "tool_error",
        oracle,
        [{"jsonrpc": "2.0", "id": 7, "method": "tools/call", "params": {"name": "fetch_url", "arguments": {"url": "http://127.0.0.1:1"}}}],
        check=args.check,
    )
    fixture_names["notifications"] = write_pair(
        root,
        "notifications",
        oracle,
        [
            {"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}},
            {"jsonrpc": "2.0", "method": "notifications/cancelled", "params": {"requestId": 1}},
            {"jsonrpc": "2.0", "method": "bogus", "params": {}},
        ],
        check=args.check,
    )
    fixture_dir.mkdir(parents=True, exist_ok=True)
    sync_file(fixture_dir / "eof.in", b"", args.check)
    sync_file(fixture_dir / "eof.out", b"", args.check)
    fixture_names["eof"] = {"input": "eof.in", "output": "eof.out"}

    all_out, all_err = run(oracle, list_request, "--tools", "all")
    if all_err:
        raise SystemExit(f"oracle wrote stderr for tools_all: {all_err!r}")
    generate_registry(root, all_out, args.check)

    manifest = {
        "schema_version": 1,
        "oracle_commit": ORACLE_COMMIT,
        "oracle_release": "v0.8.0",
        "source_files": source_hashes(root),
        "fixtures": fixture_names,
    }
    manifest_path = fixture_dir / "manifest.json"
    rendered = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    if args.check:
        expected = manifest_path.read_text(encoding="utf-8") if manifest_path.exists() else ""
        for name, paths in fixture_names.items():
            for key in ("input", "output"):
                if not (fixture_dir / paths[key]).exists():
                    raise SystemExit(f"missing MCP fixture: {paths[key]}")
        if expected != rendered:
            raise SystemExit("MCP fixture manifest is stale; run mcp_fixture_gen.py without --check")
        print("MCP fixtures are current")
        return 0
    manifest_path.write_text(rendered, encoding="utf-8")
    print(f"generated {len(fixture_names)} MCP raw-frame fixture cases")
    return 0


def write_pair_raw(root: Path, name: str, oracle: Path, data: bytes, *args: str, check: bool = False) -> dict[str, str]:
    temporary, environment = oracle_environment()
    try:
        proc = subprocess.run([str(oracle), "mcp", "--engine", "static", *args], input=data, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True, env=environment)
    finally:
        temporary.cleanup()
    if proc.stderr:
        raise SystemExit(f"oracle wrote stderr for {name}: {proc.stderr!r}")
    fixture_dir = root / "testdata" / "port" / "mcp"
    fixture_dir.mkdir(parents=True, exist_ok=True)
    sync_file(fixture_dir / f"{name}.in", data, check)
    sync_file(fixture_dir / f"{name}.out", proc.stdout, check)
    return {"input": f"{name}.in", "output": f"{name}.out"}


if __name__ == "__main__":
    raise SystemExit(main())
