// Command fetchcontrolgen freezes deterministic fetch-control behavior from Go.
//go:build rustport

package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"time"

	"github.com/danieljustus/symaira-browse/internal/fetch/fetch"
	"github.com/danieljustus/symaira-browse/internal/fetch/robots"
)

const oracleCommit = "652453d1595fc302bd69c328e7da8a21dbee28b9"

var sourceFiles = []string{
	"internal/fetch/fetch/client.go",
	"internal/fetch/fetch/backoff.go",
	"internal/fetch/fetch/honest.go",
	"internal/fetch/fetch/charset.go",
	"internal/fetch/fetch/guard.go",
	"internal/fetch/robots/robots.go",
	"internal/fetch/archive/wayback.go",
	"internal/fetch/relevance/relevance.go",
	"internal/fetch/pipeline/truncate.go",
}

type fixture struct {
	OracleCommit string   `json:"oracle_commit"`
	GeneratedBy  string   `json:"generated_by"`
	SourceDigest string   `json:"source_digest"`
	Controls     controls `json:"controls"`
}

type controls struct {
	Profiles []profileCase `json:"profiles"`
	Retry    retryControl  `json:"retry"`
	Robots   []robotsCase  `json:"robots"`
	Batch    []int         `json:"batch_counts"`
	CaseIDs  []string      `json:"case_ids"`
	Static   staticControl `json:"static"`
}

type staticControl struct {
	Mode            string       `json:"mode"`
	BrowserIdentity *string      `json:"browser_identity"`
	TLSProfile      *string      `json:"tls_profile"`
	Selection       []staticCase `json:"selection"`
	TypedErrors     []staticCase `json:"typed_errors"`
}

type staticCase struct {
	ID     string `json:"id"`
	Input  string `json:"input"`
	Result string `json:"result"`
}

type profileCase struct {
	Input   string `json:"input"`
	Profile string `json:"profile"`
	Warning string `json:"warning,omitempty"`
}

type retryControl struct {
	Transient  []statusCase `json:"transient"`
	Backoff    []delayCase  `json:"backoff"`
	RetryAfter []delayCase  `json:"retry_after"`
}

type statusCase struct {
	Status int  `json:"status"`
	Value  bool `json:"value"`
}

type delayCase struct {
	Input   string `json:"input,omitempty"`
	Attempt int    `json:"attempt,omitempty"`
	Jitter  int    `json:"jitter,omitempty"`
	Millis  int64  `json:"millis"`
}

type robotsCase struct {
	Name    string `json:"name"`
	Text    string `json:"text"`
	Agent   string `json:"agent"`
	Path    string `json:"path"`
	Allowed bool   `json:"allowed"`
}

func main() {
	out := flag.String("out", "port/fixtures/fetch/control.json", "fixture path")
	check := flag.Bool("check", false, "compare regenerated bytes with fixture")
	flag.Parse()
	result := generate()
	data, err := json.MarshalIndent(result, "", "  ")
	if err != nil {
		panic(err)
	}
	data = append(data, '\n')
	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			panic(fmt.Errorf("read fixture: %w", err))
		}
		if !bytes.Equal(existing, data) {
			panic(fmt.Sprintf("fixture drift: regenerate %s deliberately", *out))
		}
		fmt.Printf("checked %s (%d profiles, %d robots cases, source %s)\n", *out, len(result.Controls.Profiles), len(result.Controls.Robots), result.SourceDigest)
		return
	}
	if err := os.MkdirAll(filepathDir(*out), 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*out, data, 0644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s\n", *out)
}

func filepathDir(path string) string {
	for i := len(path) - 1; i >= 0; i-- {
		if path[i] == '/' {
			if i == 0 {
				return "/"
			}
			return path[:i]
		}
	}
	return "."
}

func generate() fixture {
	inputs := []string{"", "chrome", "firefox", "opera", "safari", "edge", "ios", "honest", "random", "unknown", "Chrome"}
	profiles := make([]profileCase, 0, len(inputs))
	for _, input := range inputs {
		p := fetch.ParseProfile(input)
		warning := ""
		if input != "" && input != "chrome" && input != "firefox" && input != "opera" && input != "safari" && input != "edge" && input != "ios" && input != "honest" && input != "random" {
			warning = fmt.Sprintf("unknown profile, defaulting to chrome: %s", input)
		}
		profiles = append(profiles, profileCase{Input: input, Profile: string(p), Warning: warning})
	}

	transient := make([]statusCase, 0, 13)
	for _, status := range []int{199, 200, 204, 301, 400, 404, 408, 425, 429, 500, 502, 503, 504} {
		transient = append(transient, statusCase{Status: status, Value: fetch.IsTransientError(status, nil)})
	}
	backoff := fetch.DefaultBackoffConfig()
	backoffs := make([]delayCase, 0, 12)
	for attempt := 0; attempt < 6; attempt++ {
		backoffs = append(backoffs,
			delayCase{Attempt: attempt, Jitter: 50, Millis: backoffMillis(backoff, attempt, 50)},
			delayCase{Attempt: attempt, Jitter: 100, Millis: backoffMillis(backoff, attempt, 100)})
	}
	retryAfter := []delayCase{
		{Input: "0", Millis: 0}, {Input: "12", Millis: 12_000},
		{Input: "-5", Millis: -5_000}, {Input: "invalid", Millis: 0},
	}
	robotsText := map[string]string{
		"specific-longest": "User-agent: *\nDisallow: /private\nAllow: /private/public\n\nUser-agent: symfetch\nDisallow: /all\nAllow: /all/public\n",
		"wildcard":         "User-agent: *\nDisallow: /private/*\nAllow: /private/public\n",
		"comments":         "# comment\nUser-agent: * # all\nDisallow: /secret # no\nAllow: /secret/public\n",
		"empty":            "User-agent: *\nDisallow:\n",
		"no-group":         "User-agent: crawler\nDisallow: /hidden\n",
	}
	robotsCases := make([]robotsCase, 0, len(robotsText)*3)
	for name, text := range robotsText {
		rules := robots.ParseRules(text)
		for _, query := range [][2]string{{"symfetch/1", "/all/public/page"}, {"other-client", "/private/secret"}, {"crawler", "/hidden"}} {
			robotsCases = append(robotsCases, robotsCase{Name: name, Text: text, Agent: query[0], Path: query[1], Allowed: rules.Allows(query[0], query[1])})
		}
	}
	sort.Slice(robotsCases, func(i, j int) bool {
		if robotsCases[i].Name != robotsCases[j].Name {
			return robotsCases[i].Name < robotsCases[j].Name
		}
		return robotsCases[i].Path < robotsCases[j].Path
	})
	caseIDs := []string{
		"FETCH-001-profile-selection",
		"FETCH-003-http-semantics",
		"FETCH-004-redirect-proxy-cookie",
		"FETCH-005-robots-retry-rate-limit",
		"FETCH-009-static-selection",
		"FETCH-009-browser-unavailable",
		"FETCH-009-compat-unavailable",
		"FETCH-010-static-honesty",
	}
	return fixture{
		OracleCommit: oracleCommit,
		GeneratedBy:  "scripts/rust-port/cmd/fetchcontrolgen",
		SourceDigest: sourceDigest(),
		Controls: controls{
			Profiles: profiles,
			Retry:    retryControl{Transient: transient, Backoff: backoffs, RetryAfter: retryAfter},
			Robots:   robotsCases,
			Batch:    []int{0, 1, 20, 21},
			CaseIDs:  caseIDs,
			Static: staticControl{
				Mode:            "static",
				BrowserIdentity: nil,
				TLSProfile:      nil,
				Selection: []staticCase{
					{ID: "FETCH-009-static-selection", Input: "static", Result: "selected"},
				},
				TypedErrors: []staticCase{
					{ID: "FETCH-009-browser-unavailable", Input: "browser", Result: "typed_unavailable"},
					{ID: "FETCH-009-compat-unavailable", Input: "compat", Result: "typed_unavailable"},
				},
			},
		},
	}
}

func backoffMillis(c fetch.BackoffConfig, attempt, jitter int) int64 {
	base := c.InitialDelay
	for i := 0; i < attempt; i++ {
		base = time.Duration(float64(base) * c.Multiplier)
		if base > c.MaxDelay {
			base = c.MaxDelay
		}
	}
	return int64(float64(base) * float64(jitter) / 100 / float64(time.Millisecond))
}

func sourceDigest() string {
	hash := sha256.New()
	for _, path := range sourceFiles {
		data, err := os.ReadFile(path)
		if err != nil {
			panic(err)
		}
		hash.Write([]byte(path))
		hash.Write([]byte{0})
		hash.Write(data)
		hash.Write([]byte{0})
	}
	return hex.EncodeToString(hash.Sum(nil))
}
